"""empty message

Revision ID: 381b9ed768e2
Revises: 58f2a9e9a5e1
Create Date: 2016-09-26 12:56:25.999159

"""

# revision identifiers, used by Alembic.
revision = '381b9ed768e2'
down_revision = '58f2a9e9a5e1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform', sa.Column('abstract', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform', 'abstract')
    ### end Alembic commands ###
