"""add product

Revision ID: 5634ede81dc2
Revises: e057cf02bbb6
Create Date: 2016-09-23 09:31:44.276220

"""

# revision identifiers, used by Alembic.
revision = '5634ede81dc2'
down_revision = 'e057cf02bbb6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('companyName', sa.String(length=48), nullable=True),
    sa.Column('legalRepresentative', sa.String(length=48), nullable=True),
    sa.Column('phone400', sa.String(length=48), nullable=True),
    sa.Column('phone', sa.String(length=48), nullable=True),
    sa.Column('fax', sa.String(length=48), nullable=True),
    sa.Column('email', sa.String(length=48), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=48), nullable=True),
    sa.Column('gradeFromThird', sa.String(length=48), nullable=True),
    sa.Column('profitAverage', sa.String(length=48), nullable=True),
    sa.Column('dateSale', sa.String(length=48), nullable=True),
    sa.Column('registeredCapital', sa.String(length=48), nullable=True),
    sa.Column('area', sa.String(length=48), nullable=True),
    sa.Column('url', sa.String(length=48), nullable=True),
    sa.Column('startMoney', sa.String(length=48), nullable=True),
    sa.Column('managementFee', sa.String(length=48), nullable=True),
    sa.Column('cashTakingFee', sa.String(length=48), nullable=True),
    sa.Column('backGround', sa.String(length=48), nullable=True),
    sa.Column('provisionOfRisk', sa.String(length=48), nullable=True),
    sa.Column('foundCustodian', sa.String(length=48), nullable=True),
    sa.Column('safeguardWay', sa.String(length=48), nullable=True),
    sa.Column('assignmentOfDebt', sa.String(length=48), nullable=True),
    sa.Column('automaticBidding', sa.String(length=48), nullable=True),
    sa.Column('cashTime', sa.String(length=48), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=48), nullable=True),
    sa.Column('curriculumVitae', sa.Text(), nullable=True),
    sa.Column('platform_id', sa.String(length=48), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=48), nullable=True),
    sa.Column('annualizedReturn', sa.String(length=48), nullable=True),
    sa.Column('cycle', sa.String(length=48), nullable=True),
    sa.Column('remainAmount', sa.String(length=48), nullable=True),
    sa.Column('platform_id', sa.String(length=48), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_table('person')
    op.drop_table('platform')
    op.drop_table('company')
    ### end Alembic commands ###
