"""empty message

Revision ID: 58f2a9e9a5e1
Revises: None
Create Date: 2016-09-24 00:18:35.107365

"""

# revision identifiers, used by Alembic.
revision = '58f2a9e9a5e1'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=48), nullable=True),
    sa.Column('gradeFromThird', sa.String(length=48), nullable=True),
    sa.Column('profitAverage', sa.String(length=48), nullable=True),
    sa.Column('dateSale', sa.String(length=48), nullable=True),
    sa.Column('registeredCapital', sa.String(length=48), nullable=True),
    sa.Column('area', sa.String(length=48), nullable=True),
    sa.Column('url', sa.String(length=48), nullable=True),
    sa.Column('startMoney', sa.String(length=48), nullable=True),
    sa.Column('managementFee', sa.String(length=48), nullable=True),
    sa.Column('cashTakingFee', sa.String(length=48), nullable=True),
    sa.Column('backGround', sa.String(length=48), nullable=True),
    sa.Column('provisionOfRisk', sa.String(length=48), nullable=True),
    sa.Column('foundCustodian', sa.String(length=48), nullable=True),
    sa.Column('safeguardWay', sa.String(length=48), nullable=True),
    sa.Column('assignmentOfDebt', sa.String(length=48), nullable=True),
    sa.Column('automaticBidding', sa.String(length=48), nullable=True),
    sa.Column('cashTime', sa.String(length=48), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('abstracts', sa.Text(), nullable=True),
    sa.Column('platform_id', sa.String(length=48), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=48), nullable=True),
    sa.Column('annualizedReturn', sa.String(length=48), nullable=True),
    sa.Column('cycle', sa.String(length=48), nullable=True),
    sa.Column('remainAmount', sa.String(length=48), nullable=True),
    sa.Column('platform_id', sa.String(length=48), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_table('person')
    op.drop_table('platform')
    ### end Alembic commands ###
