"""init

Revision ID: e057cf02bbb6
Revises: None
Create Date: 2016-09-22 11:11:41.711660

"""

# revision identifiers, used by Alembic.
revision = 'e057cf02bbb6'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laws',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=48), nullable=True),
    sa.Column('type', sa.String(length=48), nullable=True),
    sa.Column('publishDepartment', sa.String(length=48), nullable=True),
    sa.Column('publishDate', sa.String(length=48), nullable=True),
    sa.Column('effectDate', sa.String(length=48), nullable=True),
    sa.Column('loseEffectDate', sa.String(length=48), nullable=True),
    sa.Column('status', sa.String(length=48), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('laws')
    ### end Alembic commands ###
